### PR TITLE
adding support for DATETIME epochs

### PR DESCRIPTION
**Pull request by rekliner**
sqlite3 supports datetime fields but they were being ignored.  They might have 32bit or 64bit epoch numbers, which I've converted down to 32bit for mysql compatibility.

### CODE REVIEW

**Comment by techouse** [comment]
Hi and thanks for the submission. ♥️

Would you mind adding some tests?

**Comment by rekliner** [comment]
yeah, looks like 2.7 uses the time library rather than datetime.  I've refactored but I'm still wrapping my head around unit testing in python

**Comment by techouse** [comment]
@rekliner any progress?

**Comment by techouse** [comment]
@rekliner Take all the time you need. We all do this for the love of the community 🥳

**Comment by techouse** [comment]
@rekliner I have recently released v2.0.0 which is Python 3.7+ only and have merged it into your PR, however, there's a bug with your code:

```
sqlite3_to_mysql/sqlite_utils.py:50: in convert_epoch
    _intval = int(value)
E   ValueError: invalid literal for int() with base 10: b'2007-07-09 14:20:19.000000'
        value      = b'2007-07-09 14:20:19.000000'
```

https://github.com/techouse/sqlite3-to-mysql/actions/runs/5229946600/jobs/9443242359#step:8:6773

**Comment by rekliner** [comment]
It seems that an ISO string is being passed to the function.  I added it as a way to process [epoch time](https://www.epochconverter.com/), which was what I was getting from my sqlite files for fields identifying as DATETIME.  I'm wondering if its a difference in python or platform that it is getting the ISO string rather than a number.  It may be as simply be being tested wrong.  I'll try to find out soon.  Sorry I haven't had much time for this but I haven't forgotten.

**Comment by techouse** [comment]
No worries. :) At least now you won't have to worry about Python 2 anymore :)

**Comment by techouse** [comment]
You might want to look at how I solved this in my other repo here https://github.com/techouse/sqlite3-to-mysql/issues/36

**Pull request closed without merging**
